package com.example.util

import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.entity.CustomerEntity
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object CsvExportUtils {

    fun generateCustomerCsv(folderName: String, customers: List<CustomerEntity>): String {
        val sb = StringBuilder()
        
        // Header
        sb.append("Customer ID,Name,Phone,Book Number,Page Number,Email,Address,Status,Document Type,Document Number,Notes,Created Date\n")

        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())

        for (c in customers) {
            val formattedDate = dateFormat.format(Date(c.createdAt))
            sb.append(escapeCsv(c.id.toString())).append(",")
            sb.append(escapeCsv(c.name)).append(",")
            sb.append(escapeCsv(c.phone)).append(",")
            sb.append(escapeCsv(c.bookNumber)).append(",")
            sb.append(escapeCsv(c.pageNumber)).append(",")
            sb.append(escapeCsv(c.email)).append(",")
            sb.append(escapeCsv(c.address)).append(",")
            sb.append(escapeCsv(c.status)).append(",")
            sb.append(escapeCsv(c.documentType)).append(",")
            sb.append(escapeCsv(c.documentNumber)).append(",")
            sb.append(escapeCsv(c.notes)).append(",")
            sb.append(escapeCsv(formattedDate)).append("\n")
        }

        return sb.toString()
    }

    private fun escapeCsv(field: String?): String {
        if (field.isNullOrEmpty()) return ""
        var escaped = field.replace("\"", "\"\"")
        if (escaped.contains(",") || escaped.contains("\"") || escaped.contains("\n") || escaped.contains("\r")) {
            escaped = "\"$escaped\""
        }
        return escaped
    }

    fun exportAndShareCsv(context: Context, folderName: String, customers: List<CustomerEntity>) {
        if (customers.isEmpty()) {
            Toast.makeText(context, "No customers in this folder to export.", Toast.LENGTH_SHORT).show()
            return
        }

        try {
            val csvContent = generateCustomerCsv(folderName, customers)
            val sanitizedFolderName = folderName.replace(Regex("[^a-zA-Z0-9_-]"), "_")
            val fileName = "Customers_${sanitizedFolderName}_${System.currentTimeMillis()}.csv"

            val exportDir = File(context.cacheDir, "exports").apply { if (!exists()) mkdirs() }
            val csvFile = File(exportDir, fileName)
            csvFile.writeText(csvContent, Charsets.UTF_8)

            val contentUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                csvFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/csv"
                putExtra(Intent.EXTRA_STREAM, contentUri)
                putExtra(Intent.EXTRA_SUBJECT, "Customer List CSV Export - $folderName")
                putExtra(
                    Intent.EXTRA_TEXT,
                    "Exported customer list for folder '$folderName' (${customers.size} customers).\nGenerated by Shree Bartan Store App."
                )
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(shareIntent, "Share Customer CSV File")
            context.startActivity(chooser)

            Toast.makeText(context, "Exported ${customers.size} customer(s) to CSV", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Failed to export CSV: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }
}
